// Command formulagen renders the Homebrew formula for a correlator release.
//
// It reads the four release tarballs from -dist, computes their SHA-256
// sums, and writes Formula/correlator.rb. Dev/release tooling — not part of
// shipped binaries.
//
// Usage:
//
//	go run ./internal/devtools/formulagen -version v2.1.0 -dist ./dist [-out path]
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

const template = `# frozen_string_literal: true

# Generated by hx_netkit internal/devtools/formulagen — do not edit.

class Correlator < Formula
  desc "Network intelligence — scan, capture, and interrogate your network with local AI"
  homepage "https://github.com/hxmbl/hx_netkit"
  version "{{VERSION}}"
  license "Unlicense"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hxmbl/hx_netkit/releases/download/{{TAG}}/correlator-{{TAG}}-darwin-arm64.tar.gz"
      sha256 "{{DARWIN_ARM64}}"

      def install
        bin.install "correlator"
      end
    else
      url "https://github.com/hxmbl/hx_netkit/releases/download/{{TAG}}/correlator-{{TAG}}-darwin-amd64.tar.gz"
      sha256 "{{DARWIN_AMD64}}"

      def install
        bin.install "correlator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hxmbl/hx_netkit/releases/download/{{TAG}}/correlator-{{TAG}}-linux-arm64.tar.gz"
      sha256 "{{LINUX_ARM64}}"

      def install
        bin.install "correlator"
      end
    else
      url "https://github.com/hxmbl/hx_netkit/releases/download/{{TAG}}/correlator-{{TAG}}-linux-amd64.tar.gz"
      sha256 "{{LINUX_AMD64}}"

      def install
        bin.install "correlator"
      end
    end
  end

  def caveats
    <<~EOS
      Packet capture needs TShark and Nmap:
        brew install wireshark nmap

      Local AI chat needs Ollama plus a model:
        brew install ollama
        ollama pull qwen3:4b
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/correlator version")
  end
end
`

func sha256File(path string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer f.Close()
	h := sha256.New()
	if _, err := io.Copy(h, f); err != nil {
		return "", err
	}
	return hex.EncodeToString(h.Sum(nil)), nil
}

func main() {
	version := flag.String("version", "", "release version WITHOUT leading v (e.g. 2.1.0)")
	dist := flag.String("dist", "./dist", "directory containing correlator-<tag>-<goos>-<goarch>.tar.gz files")
	out := flag.String("out", "-", "output path ('-' = stdout)")
	flag.Parse()

	if *version == "" {
		fmt.Fprintln(os.Stderr, "-version is required")
		os.Exit(2)
	}
	tag := "v" + strings.TrimPrefix(*version, "v")

	sums := map[string]string{}
	for _, p := range []struct{ goos, goarch string }{{"darwin", "arm64"}, {"darwin", "amd64"}, {"linux", "amd64"}, {"linux", "arm64"}} {
		name := fmt.Sprintf("correlator-%s-%s-%s.tar.gz", tag, p.goos, p.goarch)
		sum, err := sha256File(filepath.Join(*dist, name))
		if err != nil {
			fmt.Fprintf(os.Stderr, "missing %s: %v\n", name, err)
			os.Exit(1)
		}
		key := strings.ToUpper(p.goos) + "_" + strings.ToUpper(p.goarch)
		sums[key] = sum
	}

	text := template
	text = strings.ReplaceAll(text, "{{VERSION}}", *version)
	text = strings.ReplaceAll(text, "{{TAG}}", tag)
	text = strings.ReplaceAll(text, "{{DARWIN_ARM64}}", sums["DARWIN_ARM64"])
	text = strings.ReplaceAll(text, "{{DARWIN_AMD64}}", sums["DARWIN_AMD64"])
	text = strings.ReplaceAll(text, "{{LINUX_ARM64}}", sums["LINUX_ARM64"])
	text = strings.ReplaceAll(text, "{{LINUX_AMD64}}", sums["LINUX_AMD64"])

	if strings.Contains(text, "{{") {
		fmt.Fprintln(os.Stderr, "unresolved placeholders in output")
		os.Exit(1)
	}

	if *out == "-" {
		fmt.Print(text)
		return
	}
	if err := os.MkdirAll(filepath.Dir(*out), 0o755); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if err := os.WriteFile(*out, []byte(text), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "wrote %s\n", *out)
}
